---
functional:
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности. 
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи и интерфейс доступны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Пользователь может зарегистрироваться на сайте через GitHub, Discord, почту и пароль
  - Игру может создать только авторизированный пользователь
  - Игра поддерживает отложенный выбор языка программирования
  - Игра отображается в списке “доступных для подключения”.
  - Второй игрок подключается по нажатию “Connect to game”.
  - В режиме игры два редактора слева — свой, справа — соперника.
  - Синхронизация кода в реальном времени (видно, что печатает соперник).
  - Есть отдельный чат игры
  - Кнопка “Check” — неограниченное количество попыток.
  - Поддержка переподключения при разрыве соединения.
  - Состояние игры - active, finished (один победил), closed (оба вышли). 
  - Есть предыгровая страница и страница со списком игр
  - Добавлено окно вывода результатов проверки кода и показом задания в разных табах
  - В игре возможно сдаться
  - В игре есть всплывающие сообщения о результате проверки и выигрыше игрока
  - Есть информация о турнирах

